% This is the configuration template file for individual analysis 
% _________________________________________________________________________
% 2009-2012 Stanford Cognitive and Systems Neuroscience Laboratory
%
% $Id: individualstats_config.m.template, Tianwen Chen, 2012-06-06 $
% -------------------------------------------------------------------------

% Please specify the data type of preprocessed images
% 'nii' for Nifti 4-D format, 'img' for Analyze 7.5 format
% If you would like the script to decide which type to use, uncomment the 
% second line and comment the first line
paralist.data_type = 'nii';
% paralist.data_type = [''];

% Please specify the standard preprocessing pipeline you have used
paralist.pipeline = 'swcar';
%paralist.pipeline = 'shortened_swar';

% Please specify the raw data server
paralist.server_path = '/home/qinlab/data';
 
% Please specify the individualstats server
paralist.stats_path = '/home/qinlab/data/genghaiyang/data/nback/individualstats_SPM12';

% Please specify the parent folder of the static data
% For YEAR data structure, use the first one
% For NONE YEAR data structure, use the second one
paralist.parent_folder   = '';
% paralist.parent_folder = 'UCSFBoxer'

% Please specify the .txt file or a cell arry of subjects
paralist.subjectlist     = {'11-12-05.2';'11-12-06.1';'11-12-12.3';'11-12-21.1'};
%{'11-11-15.1';'11-11-16.1';'11-11-16.3';'11-11-18.1';'11-11-18.2';'11-11-18.3';'11-11-21.1';'11-11-21.2';'11-11-21.3';'11-11-22.1';'11-11-22.2';'11-11-22.3';'11-11-23.1';'11-11-23.2';'11-11-23.3';'11-11-25.1';'11-11-25.2';'11-11-25.3';'11-11-28.1';'11-11-28.2';'11-11-28.3';'11-11-29.1';'11-11-29.2';'11-11-29.3';'11-11-30.1';'11-11-30.2';'11-11-30.3';'11-12-02.1';'11-12-02.2';'11-12-02.3';'11-12-05.1';'11-12-06.2';'11-12-07.1';'11-12-07.2';'11-12-07.3';'11-12-09.1';'11-12-09.2';'11-12-12.1';'11-12-12.2';'11-12-13.1';'11-12-13.2';'11-12-13.3';'11-12-21.2';'11-12-21.3';'11-12-22.1';'11-12-22.2';'11-12-22.3';'11-12-26.1';'11-12-26.2';'11-12-26.3';'11-12-27.1';'11-12-27.2';'11-12-27.3';'11-12-28.1';'11-12-28.2';'11-12-28.3'};%{'subjectlist_discard.txt'};
%paralist.subjectlist     = {'11-11-25.s100'};

% Please specify the .txt file or a cell array of exp_sessions
paralist.exp_sesslist    = 'nback';

% Please specify the task design file (*.m)
paralist.task_dsgn       = 'taskdesign_nback.m';

% Please specify the file holding contrasts
paralist.contrastmat     = '/home/qinlab/SPM/spm8_scripts/Qin_code/contrasts_nback.mat';
%paralist.contrastmat = ['']; 

% Please specify the foler for preprocessed data via standard pipeline
paralist.preprocessed_folder    = 'smoothed_spm8';

% Please specify the folder holding statistics results (below 'stats_spm' 
% which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
paralist.stats_folder = 'nback/stats_spm8_swcar';
% paralist.stats_folder = 'temp_stats';

% Please indicate whether to use head movements (1:Yes; 0:No)
paralist.include_mvmnt = 1;

% Please indicate whether it is based on VolRepair pipeline
% 1: use volrepair pipeline data for individual stats
% 0: use standard pipeline data
% If you set volrepair = 1, set up VolRepair section below
% If you set volrepair = 0, do not set up VolRepair section below 
paralist.include_volrepair = 0;

% -------------------------------------------------------------------------
% VolRepair Preprocessing Setup
% -------------------------------------------------------------------------

% Please specify the volrepair preprocessing pipeline
paralist.volpipeline = 'swavr';

% Please specify the volrepair preprocessed folder
paralist.volrepaired_folder = 'volrepair_spm8';

% Please specify the folder for VolRepaired data (swavrI*)
% the stats folder is under 'stats_spm8' folder (generated by default)
paralist.repaired_stats   = 'stats_spm8_VolRepair';

% -------------------------------------------------------------------------

% Please specify the folder holding batch templates
%paralist.template_path    = '/home/fmri/fmrihome/SPM/spm8_scripts/BatchTemplates';
paralist.template_path    = '/home/qinlab/SPM/spm8_scripts/BatchTemplates'; %Shaozheng added

